"""Static catalog data for data-moat indicators.

Pure data extracted from market_indicators.py: indicator definitions, tier
key tuples, and country/currency mapping tables. No DB or network coupling.
"""

from __future__ import annotations

from typing import Any

INDICATOR_DEFINITIONS: list[dict[str, Any]] = [
    {
        "key": "promo_intensity",
        "name": "Promo Intensity",
        "category": "retail",
        "source": "internal:price_snapshots",
        "unit": "pct",
        "refresh_hours": 8,
        "description": "Share of indexed SKUs with an active discount (list_price > price).",
        "formula": "count(discount>0) / count(price>0) * 100",
    },
    {
        "key": "price_dispersion",
        "name": "Price Dispersion",
        "category": "retail",
        "source": "internal:price_snapshots",
        "unit": "pct",
        "refresh_hours": 8,
        "description": "Average coefficient of variation for comparable product names across stores.",
        "formula": "mean(std(prices)/mean(prices)) * 100 per product cluster",
    },
    {
        "key": "basket_stress_index",
        "name": "Basket Stress Index (BSI)",
        "category": "affordability",
        "source": "internal:price_snapshots",
        "unit": "index",
        "refresh_hours": 8,
        "description": (
            "Minimum canasta básica total (10 staples) vs 30-day rolling baseline. "
            "Normalized score (0–1+): <0.15 stable, 0.15–0.50 moderate pressure, >0.50 critical. "
            "Raw index: current_min_basket / baseline_min_basket * 100 (100 = baseline parity)."
        ),
        "formula": "min_canasta_total / baseline_canasta_total * 100",
        "scale_note": "Normalized 0–1+: <0.15 stable · 0.15–0.50 moderate · >0.50 critical. Raw index ~100 = baseline parity.",
    },
    {
        "key": "search_momentum",
        "name": "Search Momentum",
        "category": "demand",
        "source": "internal:search_queries",
        "unit": "ratio",
        "refresh_hours": 24,
        "description": "Ratio of search volume last 7d vs prior 7d.",
        "formula": "searches_7d / max(searches_prev_7d, 1)",
    },
    {
        "key": "moat_freshness",
        "name": "Moat Freshness",
        "category": "quality",
        "source": "internal:price_snapshots",
        "unit": "pct",
        "refresh_hours": 8,
        "description": "Share of catalog stores with at least one price snapshot in the last 24 hours.",
        "formula": "count(DISTINCT store where queried_at>=now-24h) / catalog_stores * 100",
    },
    {
        "key": "store_coverage",
        "name": "Store Coverage",
        "category": "quality",
        "source": "internal:price_snapshots",
        "unit": "count",
        "refresh_hours": 8,
        "description": "Distinct stores with at least one valid price in the moat.",
        "formula": "count(distinct store where price>0)",
    },
    {
        "key": "fx_usd_local",
        "name": "USD Exchange Rate",
        "category": "macro",
        "source": "external:open.er-api.com",
        "unit": "rate",
        "refresh_hours": 24,
        "description": "Latest USD to local currency rate (public FX API).",
        "formula": "GET https://open.er-api.com/v6/latest/USD → rates[CCY]",
    },
    {
        "key": "cpi_official_yoy",
        "name": "Official CPI YoY",
        "category": "macro",
        "source": "external:worldbank",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "World Bank FP.CPI.TOTL.ZG — annual inflation, official benchmark.",
        "formula": "World Bank API indicator FP.CPI.TOTL.ZG",
    },
    {
        "key": "food_price_index",
        "name": "Food Price Index",
        "category": "macro",
        "source": "external:worldbank",
        "unit": "index",
        "refresh_hours": 168,
        "description": "World Bank AG.PRD.FOOD.XD — food production price index proxy.",
        "formula": "World Bank API indicator AG.PRD.FOOD.XD",
    },
    {
        "key": "collector_vs_official_gap",
        "name": "Shelf Signal vs Official CPI Gap",
        "category": "composite",
        "source": "computed",
        "unit": "pp",
        "refresh_hours": 24,
        "description": (
            "Difference (pp) between CLI Market 30-day rolling shelf price signal and the "
            "World Bank annual CPI YoY for the same country. "
            "IMPORTANT: these are methodologically distinct — shelf signal uses online prices "
            "over 30 days; CPI is an annual figure from a national household-survey basket. "
            "Do not interpret as equivalent measures. Use for directional context only."
        ),
        "formula": "internal_inflation_avg_30d_pct - cpi_official_yoy_annual",
        "period_caveat": (
            "Temporal mismatch: internal signal = 30-day rolling; official CPI = annual YoY. "
            "Comparison is directional, not equivalent."
        ),
    },
    {
        "key": "off_match_rate",
        "name": "Open Food Facts Match Rate",
        "category": "product",
        "source": "external:openfoodfacts",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Share of sampled supermercados SKUs matched in Open Food Facts.",
        "formula": "matched_samples / ENRICH_SAMPLE_SIZE * 100",
    },
    {
        "key": "off_nutriscore_ab_pct",
        "name": "Nutri-Score A/B Share",
        "category": "product",
        "source": "external:openfoodfacts",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Among OFF matches, percentage with Nutri-Score A or B.",
        "formula": "count(nutriscore in A,B) / matched * 100",
    },
    {
        "key": "off_nova_avg",
        "name": "NOVA Group Average",
        "category": "product",
        "source": "external:openfoodfacts",
        "unit": "score",
        "refresh_hours": 168,
        "description": "Average NOVA processing group (1=minimal … 4=ultra-processed).",
        "formula": "mean(nova_group) over OFF matches",
    },
    {
        "key": "wiki_demand_momentum",
        "name": "Wikipedia Demand Momentum",
        "category": "demand",
        "source": "external:wikimedia",
        "unit": "ratio",
        "refresh_hours": 24,
        "description": "7d vs prior 7d pageviews for staple food terms (country wiki).",
        "formula": "mean(recent_views / prior_views) per article",
    },
    {
        "key": "weather_logistics_stress",
        "name": "Weather Logistics Stress",
        "category": "logistics",
        "source": "external:open-meteo.com",
        "unit": "index",
        "refresh_hours": 12,
        "description": "7-day precipitation + heat stress proxy for capital city (fresh goods logistics).",
        "formula": "min(100, rain_mm*2.5 + heat_days*8)",
    },
    {
        "key": "food_cpi_yoy",
        "name": "Official Food CPI YoY",
        "category": "macro",
        "source": "external:worldbank",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "World Bank FP.CPI.FOOD.ZG — food inflation official benchmark.",
        "formula": "World Bank API FP.CPI.FOOD.ZG",
    },
    {
        "key": "off_ultra_processed_pct",
        "name": "Ultra-Processed Share (NOVA 4)",
        "category": "product",
        "source": "external:openfoodfacts",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Among OFF matches, percentage classified NOVA group 4 (ultra-processed).",
        "formula": "count(nova_group=4) / matched * 100",
    },
    {
        "key": "food_inflation_spread",
        "name": "Food vs Headline CPI Spread",
        "category": "composite",
        "source": "computed",
        "unit": "pp",
        "refresh_hours": 168,
        "description": "Official food CPI YoY minus headline CPI YoY — food inflation premium.",
        "formula": "food_cpi_yoy - cpi_official_yoy",
    },
    {
        "key": "wiki_staple_momentum",
        "name": "Staple Wikipedia Momentum",
        "category": "demand",
        "source": "external:wikimedia",
        "unit": "ratio",
        "refresh_hours": 24,
        "description": "7d vs prior 7d pageviews for leche/arroz/aceite articles.",
        "formula": "mean(recent/prior) for staple wiki articles",
    },
    {
        "key": "staple_price_momentum",
        "name": "Retail Price Velocity (RPV)",
        "category": "affordability",
        "source": "internal:price_history",
        "unit": "pct",
        "refresh_hours": 8,
        "description": (
            "Average % price change for canasta staple SKUs over the last 7 days, "
            "computed from paired price_history observations per (store, product_id). "
            "Measures short-term shelf price momentum — NOT equivalent to official CPI. "
            "Only includes retailers with ≥3 snapshots in the period."
        ),
        "formula": "mean((price_last - price_first) / price_first * 100) for staple SKUs with ≥2 observations in window",
        "methodology_note": (
            "CLI Market RPV ≠ CPI. RPV captures online-channel price velocity over a 7-day window. "
            "Official inflation (INEI, INDEC, etc.) uses annual or monthly household-survey baskets. "
            "Do not annualize RPV or compare directly against official CPI figures."
        ),
    },
    {
        "key": "off_ecoscore_avg",
        "name": "Eco-Score Average",
        "category": "product",
        "source": "external:openfoodfacts",
        "unit": "score",
        "refresh_hours": 168,
        "description": "Average Eco-Score (A=5 … E=1) among OFF matches.",
        "formula": "mean(ecoscore mapped 1-5) over OFF matches",
    },
    {
        "key": "subcat_price_momentum",
        "name": "Subcategory Price Momentum",
        "category": "affordability",
        "source": "internal:price_history",
        "unit": "pct",
        "refresh_hours": 8,
        "description": "7d price change for a canasta subcategory (scope: {CC}:subcat:{item}).",
        "formula": "mean delta_pct per SKU in subcategory bucket",
    },
    {
        "key": "subcat_wiki_momentum",
        "name": "Subcategory Wiki Momentum",
        "category": "demand",
        "source": "external:wikimedia",
        "unit": "ratio",
        "refresh_hours": 24,
        "description": "Wikipedia pageview momentum for staple article (per subcategory scope).",
        "formula": "recent_views / prior_views for subcat wiki title",
    },
    {
        "key": "subcat_min_price",
        "name": "Subcategory Min Shelf Price",
        "category": "affordability",
        "source": "internal:price_snapshots",
        "unit": "local",
        "refresh_hours": 8,
        "description": "Cheapest indexed SKU in subcategory across country stores.",
        "formula": "min(price) where name matches subcategory bucket",
    },
    {
        "key": "imf_inflation_yoy",
        "name": "IMF Inflation YoY",
        "category": "macro",
        "source": "external:imf.org",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "IMF DataMapper PCPIPCH — tier-2 cross-check vs World Bank CPI.",
        "formula": "IMF external/datamapper/api/v1/PCPIPCH",
    },
    {
        "key": "eurostat_food_hicp_yoy",
        "name": "Eurostat Food HICP YoY",
        "category": "macro",
        "source": "external:ec.europa.eu/eurostat",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "EU harmonized food inflation (IT, FR) — tier 2.",
        "formula": "PRC_HICP_MANR coicop=CP01 latest annual rate",
    },
    {
        "key": "bcb_food_inflation_mom",
        "name": "BCB Food IPCA MoM",
        "category": "macro",
        "source": "external:bcb.gov.br",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Brazil central bank food IPCA month-over-month (BR only).",
        "formula": "BCB series 1635 latest month",
    },
    {
        "key": "macro_unemployment_rate",
        "name": "Unemployment Rate",
        "category": "macro",
        "source": "external:worldbank",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "World Bank SL.UEM.TOTL.ZS — labor market tier-2 context.",
        "formula": "World Bank unemployment % of labor force",
    },
    {
        "key": "imf_wb_cpi_gap",
        "name": "IMF vs World Bank CPI Gap",
        "category": "composite",
        "source": "computed",
        "unit": "pp",
        "refresh_hours": 168,
        "description": "IMF inflation minus World Bank official CPI — tier-2 validation spread.",
        "formula": "imf_inflation_yoy - cpi_official_yoy",
    },
    {
        "key": "imf_gdp_growth_yoy",
        "name": "IMF GDP Growth YoY",
        "category": "macro",
        "source": "external:imf.org",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "IMF DataMapper NGDP_RPCH — real GDP growth forecast/outturn.",
        "formula": "IMF NGDP_RPCH latest year",
    },
    {
        "key": "imf_epi_inflation_yoy",
        "name": "IMF End-Period Inflation YoY",
        "category": "macro",
        "source": "external:imf.org",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "IMF PCPIEPCH — CPI inflation end-of-period (tier-2 complement).",
        "formula": "IMF PCPIEPCH latest year",
    },
    {
        "key": "wb_gdp_growth_yoy",
        "name": "World Bank GDP Growth YoY",
        "category": "macro",
        "source": "external:worldbank",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "World Bank NY.GDP.MKTP.KD.ZG — tier-2 growth context.",
        "formula": "World Bank GDP growth annual %",
    },
    {
        "key": "eurostat_headline_hicp_yoy",
        "name": "Eurostat Headline HICP YoY",
        "category": "macro",
        "source": "external:ec.europa.eu/eurostat",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "All-items HICP annual rate (IT, FR) — tier 2.",
        "formula": "PRC_HICP_MANR coicop=CP00",
    },
    {
        "key": "bcb_headline_inflation_mom",
        "name": "BCB Headline IPCA MoM",
        "category": "macro",
        "source": "external:bcb.gov.br",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Brazil central bank headline IPCA month-over-month (BR only).",
        "formula": "BCB series 433 latest month",
    },
    {
        "key": "fx_ars_blue_gap",
        "name": "ARS Official vs Blue FX Gap",
        "category": "macro",
        "source": "external:bluelytics.com.ar",
        "unit": "pct",
        "refresh_hours": 12,
        "description": "Argentina blue vs official USD rate gap — invalidates nominal AR basket without it.",
        "formula": "(blue - oficial) / oficial * 100 from bluelytics v2/latest",
    },
    {
        "key": "bcrp_inflation_expectation_12m",
        "name": "BCRP Inflation Expectation 12m",
        "category": "macro",
        "source": "external:bcrp.gob.pe",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "BCRP Encuesta de Expectativas — inflación esperada a 12 meses (PE).",
        "formula": "BCRP series PD12912AM latest",
    },
    {
        "key": "bcrp_reference_rate",
        "name": "BCRP Reference Policy Rate",
        "category": "macro",
        "source": "external:bcrp.gob.pe",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "BCRP tasa de referencia de política monetaria (PE).",
        "formula": "BCRP series PD04722MM latest",
    },
    {
        "key": "fuel_price_index_pe",
        "name": "Fuel Price Index (PE)",
        "category": "logistics",
        "source": "external:osinergmin.gob.pe",
        "unit": "index",
        "refresh_hours": 168,
        "description": "Peru gasoline/diesel price proxy — real distribution cost vs weather-only stress.",
        "formula": "OSINERGMIN public fuel prices Lima (gasolina + diésel avg)",
    },
    {
        "key": "commodity_input_pressure",
        "name": "Commodity Input Pressure",
        "category": "macro",
        "source": "external:worldbank+faostat",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "YoY % change in global food commodity price index — leading input cost pressure.",
        "formula": "Δ% World Bank AG.PRD.FOOD.XD (FAOSTAT FP proxy when blocked)",
    },
    {
        "key": "real_wage_basket_ratio",
        "name": "Real Wage vs Basket Ratio",
        "category": "affordability",
        "source": "external:cepalstat",
        "unit": "index",
        "refresh_hours": 168,
        "description": "CEPAL food purchasing power of minimum wage vs shelf basket stress.",
        "formula": "CEPAL 2741 or real minimum wage (340) / basket_stress_index",
    },
    {
        "key": "ipp_food_co",
        "name": "Colombia Food Producer Price Index",
        "category": "macro",
        "source": "external:dane+worldbank",
        "unit": "pct",
        "refresh_hours": 168,
        "description": "Colombia food producer price pressure (DANE IPP food; WB food CPI YoY fallback).",
        "formula": "FP.CPI.FOOD.ZG CO (IPP proxy until DANE REST live)",
    },
    {
        "key": "gtrends_search_momentum",
        "name": "Google Trends Staple Momentum",
        "category": "demand",
        "source": "external:google trends",
        "unit": "ratio",
        "refresh_hours": 24,
        "description": "Google Trends daily RSS staple keyword hits vs 7d cached baseline.",
        "formula": "staple_hits_today / max(staple_hits_7d_ago, 1)",
    },
    {
        "key": "bcrp_shelf_gap",
        "name": "BCRP vs Shelf Inflation Gap",
        "category": "composite",
        "source": "computed",
        "unit": "pp",
        "refresh_hours": 168,
        "description": "Peru: BCRP 12m inflation expectation minus staple shelf momentum.",
        "formula": "bcrp_inflation_expectation_12m - staple_price_momentum",
    },
    {
        "key": "commodity_transmission_lag",
        "name": "Commodity Transmission Lag",
        "category": "composite",
        "source": "computed",
        "unit": "pp",
        "refresh_hours": 168,
        "description": "Global commodity input pressure minus shelf staple momentum — leading signal.",
        "formula": "commodity_input_pressure - staple_price_momentum",
    },
]

ENRICHMENT_INDICATOR_KEYS: tuple[str, ...] = (
    "off_match_rate",
    "off_nutriscore_ab_pct",
    "off_nova_avg",
    "off_ultra_processed_pct",
    "off_ecoscore_avg",
    "wiki_demand_momentum",
    "wiki_staple_momentum",
    "weather_logistics_stress",
    "food_cpi_yoy",
    "food_inflation_spread",
    "staple_price_momentum",
    "imf_inflation_yoy",
    "eurostat_food_hicp_yoy",
    "bcb_food_inflation_mom",
    "macro_unemployment_rate",
    "imf_wb_cpi_gap",
    "imf_gdp_growth_yoy",
    "imf_epi_inflation_yoy",
    "wb_gdp_growth_yoy",
    "eurostat_headline_hicp_yoy",
    "bcb_headline_inflation_mom",
)

TIER2_INDICATOR_KEYS: tuple[str, ...] = (
    "imf_inflation_yoy",
    "eurostat_food_hicp_yoy",
    "eurostat_headline_hicp_yoy",
    "bcb_food_inflation_mom",
    "bcb_headline_inflation_mom",
    "macro_unemployment_rate",
    "imf_wb_cpi_gap",
    "imf_gdp_growth_yoy",
    "imf_epi_inflation_yoy",
    "wb_gdp_growth_yoy",
)

COUNTRY_CURRENCY: dict[str, str] = {
    "PE": "PEN",
    "AR": "ARS",
    "MX": "MXN",
    "CO": "COP",
    "CL": "CLP",
    "BR": "BRL",
    "IT": "EUR",
    "FR": "EUR",
    "US": "USD",
}

WB_COUNTRY: dict[str, str] = {
    "PE": "PE",
    "AR": "AR",
    "MX": "MX",
    "CO": "CO",
    "CL": "CL",
    "BR": "BR",
    "IT": "IT",
    "FR": "FR",
    "US": "US",
}
